# NumPy
* numerical python
* NumPy operates on Arrays on Lists
* for performance advantages
* turning data into series of numbers

In [1]:
import numpy as np

## Data Types & Attributes

* main data type is ndarray(n-dimmensional array)

In [2]:
a1= np.array([1,2,3,4,5])
type(a1)

numpy.ndarray

In [3]:
a2= np.array(
    [[[1,2,3,4,5],
     [2,4,6,8,10]],
    [[10,20,30,40,50],
     [20,40,60,80,100]]]
            )

In [4]:
a2.ndim

3

In [5]:
a3=np.array([
    [['hello','my','name'],
     ['is','nilesh','what'],
     ['is','your','name']],
    [['hai','batao','bolo'],
     ['kuch','to','tum'],
     ['tum','ho','pagal']],
    [['mai','to','hu'],
     ['pagal','yeh','kahu'],
     ['har','pal','bsdk']]
]
)

a3.ndim

3

In [6]:
sample_array=np.array([1,2,3])
sample_array,sample_array.dtype, type(sample_array)

(array([1, 2, 3]), dtype('int32'), numpy.ndarray)

In [7]:
ones=np.ones((2,3,3),dtype=None)
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
range_array=np.arange(1,12,2)
range_array

array([ 1,  3,  5,  7,  9, 11])

In [9]:
rand1=np.random.random((5,3))
rand1

array([[0.57617852, 0.07229108, 0.06804179],
       [0.49776874, 0.91745676, 0.01736252],
       [0.61065786, 0.90472639, 0.89000562],
       [0.07933744, 0.6207303 , 0.8500647 ],
       [0.63158644, 0.03657231, 0.527158  ]])

In [29]:
rand2=np.random.randint(0,6,(3,3,2))
rand2


array([[[1, 3],
        [1, 0],
        [5, 3]],

       [[3, 0],
        [2, 3],
        [4, 0]],

       [[3, 2],
        [4, 4],
        [1, 3]]])

In [44]:
rand3=np.random.rand((3,3)
rand3

SyntaxError: invalid syntax (Temp/ipykernel_19084/2980808484.py, line 2)

In [40]:
rand3

array([[0.82128234, 0.69922673, 0.18649241],
       [0.88727266, 0.88343906, 0.0221904 ],
       [0.37643959, 0.94663199, 0.32635411]])

In [49]:
np.random.seed(12)
rand4=np.random.random((6,6))
rand4

array([[0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496,
        0.91874701],
       [0.90071485, 0.03342143, 0.95694934, 0.13720932, 0.28382835,
        0.60608318],
       [0.94422514, 0.85273554, 0.00225923, 0.52122603, 0.55203763,
        0.48537741],
       [0.76813415, 0.16071675, 0.76456045, 0.0208098 , 0.13521018,
        0.11627302],
       [0.30989758, 0.67145265, 0.47122978, 0.8161683 , 0.28958678,
        0.73312598],
       [0.70262236, 0.32756948, 0.33464753, 0.97805808, 0.62458211,
        0.95031352]])