# Intoduction to Scikit Learn

### what we are going to learn

0. end to end scikit learn workflow
1. getting the data ready
2. choose the right estimator
3. fit the model/algorith and use it to make prediction
4. Evaluating the model
5. Improve the model
6. Save and load the model
7. Putting all together

## 0. end to end scikit learn workflow

In [39]:
1.
#getting the data ready

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

h_d=pd.read_csv("heart-disease.csv")
h_d

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [19]:
2.
#defining the features column and the target column

#features table

x=h_d.drop("target",axis=1)
x

# target column

y=h_d["target"]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [16]:
#this is a classification problem as we need to classify if someone has heart disease or not
# hence, we need to choose a model as per the usage
# choosing right model and hyperparameters

from sklearn.ensemble import RandomForestClassifier

# RandomForestClassifier is a classification ML model. Its capable of learning patterns in data 
# and then classifying a sample aka row is one thing or other

clf=RandomForestClassifier() # instantiation

clf.get_params()


{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [34]:
3. 
# fitting the model to training data
from sklearn.model_selection import train_test_split # to divide the exisiting data into training and testing data

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
116   41    1   2       130   214    0        0      168      0      2.0   
216   62    0   2       130   263    0        1       97      0      1.2   
234   70    1   0       130   322    0        0      109      0      2.4   
140   51    0   2       120   295    0        0      157      0      0.6   
86    68    1   2       118   277    0        1      151      0      1.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
176   60    1   0       117   230    1        1      160      1      1.4   
6     56    0   1       140   294    0        0      153      0      1.3   
294   44    1   0       120   169    0        1      144      1      2.8   
43    53    0   0       130   264    0        0      143      0      0.4   
118   46    0   1       105   204    0        1      172      0      0.0   

     slope  ca  thal  
116      1   0     2  
216      1   1     3  
234      1   3     2  
140      2   0     2  
86       2   1     3  
..     ...  ..   ...  
176      2   2     3  
6        1   0     2  
294      0   0     1  
43       1   0     2  
118      2   0     2  

[242 rows x 13 columns]

In [33]:
# now fitting the training data into the ml model
clf.fit(x_train,y_train)

RandomForestClassifier()

In [52]:
# making a prediction
y_label=np.array([35,1,2,140,200,1,1,155,1,1.3,2,1])
y_label.reshape(-1,1)


array([[ 35. ],
       [  1. ],
       [  2. ],
       [140. ],
       [200. ],
       [  1. ],
       [  1. ],
       [155. ],
       [  1. ],
       [  1.3],
       [  2. ],
       [  1. ]])

In [56]:
y_predict=clf.predict(x_test)
y_predict

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0], dtype=int64)

In [57]:
y_test

4      1
17     1
26     1
200    0
72     1
      ..
227    0
79     1
91     1
81     1
248    0
Name: target, Length: 61, dtype: int64

In [65]:
# 4. Evaluating the model on the training data and test data
clf.score(x_train,y_train)

0.9504132231404959

In [64]:
# The sklearn. metrics module implements several loss, score, and utility functions to "measure classification performance" .

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [66]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.96      0.92      0.94        24
           1       0.95      0.97      0.96        37

    accuracy                           0.95        61
   macro avg       0.95      0.94      0.95        61
weighted avg       0.95      0.95      0.95        61



In [67]:
confusion_matrix(y_test,y_predict)

array([[22,  2],
       [ 1, 36]], dtype=int64)

In [69]:
import sklearn
sklearn.show_versions()


System:
    python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\niles\Desktop\sample_project\env\python.exe
   machine: Windows-10-10.0.19043-SP0

Python dependencies:
          pip: 21.2.4
   setuptools: 58.0.4
      sklearn: 1.0.2
        numpy: 1.21.5
        scipy: 1.7.3
       Cython: None
       pandas: 1.4.1
   matplotlib: 3.5.1
       joblib: 1.1.0
threadpoolctl: 2.2.0

Built with OpenMP: True
